#include "gfx_lookup.h"

/**
  * This file was auto-generated by gen_lookup.py!
  *
  * This lookup table handles the conversion from a pair of 2bpp mono pixels, to a pair of 16-bit bgr565 format pixels used natively by the TFT.
  * Each 2-bit pixel expands to the equivalent value:
  *   - The range of value in a 2-bit integer is [0,3]
  *   - Equivalent on-screen brightness translates to "off", "33% bright", "66% bright", "100% bright"
  *   - Each channel in the resulting bgr565 pixel needs corresponding brightness values as they're monochrome
  *   - For B and R, 5-bit, this corresponds to 0, 10, 20, 31
  *   - For G, 6-bit, this corresponds to 0, 21, 42, 63
  *   - Fully composed as bitmasks, this results in pixel values of 0x0000, 0x52AA, 0xA554, 0xFFFF
  * This table matches a single nibble of each byte specified in the pixel data, i.e. a pair of pixels:
  *   - Two 2-bit pixels at a time means the result is a pair of two 16-bit bgr565 pixels -- a single uint32_t is used to describe both in one value
  *   - Originally, this was a 256-entry uint64_t array, and allowed expanding all 4 pixels for an input byte in a single operation
  *   - The 64-bit table used a lot more flash space.
  */

const uint32_t mono2bpp_lookup[16] = {
    0x00000000, 0x0000AA52, 0x000054A5, 0x0000FFFF,
    0xAA520000, 0xAA52AA52, 0xAA5254A5, 0xAA52FFFF,
    0x54A50000, 0x54A5AA52, 0x54A554A5, 0x54A5FFFF,
    0xFFFF0000, 0xFFFFAA52, 0xFFFF54A5, 0xFFFFFFFF,
};
